#!/bin/sh -eu

realpath() {
    if [ "$(uname -s)" = "Darwin" ]; then
        perl -e 'use Cwd "abs_path";print abs_path(shift)' "$1"
    else
        readlink -f "$1"
    fi
}

ERL=$(which erl || true)
if [ "$ERL" = "" ]; then
    echo "ERROR: Cannot find Erlang, which is required to run Guild" >&2
    exit 1
fi

REAL_ERL=$(realpath $ERL)
export ROOTDIR=${REAL_ERL%/*/*}
export BINDIR=$(echo $ROOTDIR/erts-*/bin)

SCRIPT=$(realpath $0)
SCRIPTDIR=${SCRIPT%/*}
export ERL_LIBS=$SCRIPTDIR/../build/default/lib

export EMU=beam
export PROGNAME=$0

exec $BINDIR/erlexec +B -boot start_clean -noshell -run guild main -extra "$@"
