#!/bin/bash -eu

block-insert() {
    local file=$1
    local block_start=$2
    local block_end=$3
    local content=$4
    if ! grep -q -- "$content" $file; then
        sed  -i -e "/$block_start/{:a;n;/$block_end/!ba;i$content" -e "}" $file
    fi
}

block-insert \
    priv/components/vz-line-chart/vz-line-chart.html \
    '\#tooltip {' '}' \
    '\        @apply(--vz-chart-tooltip);'

block-insert \
    priv/components/tf-dashboard-common/tf-multi-checkbox.html \
    '\#outer-container {' '}' \
    '\      @apply(--tf-multi-checkbox-outer-container);'

block-insert \
    priv/components/tf-dashboard-common/tf-sidebar-helper.html \
    '\.sidebar-section {' '}' \
    '\        @apply(--tf-sidebar-helper-sidebar-section);'

block-insert \
    priv/components/tf-dashboard-common/tf-sidebar-helper.html \
    '\.sidebar-section:first-child {' '}' \
    '\        @apply(--tf-sidebar-helper-first-sidebar-section);'

block-insert \
    priv/components/tf-dashboard-common/tf-regex-group.html \
    '\.regex-input {' '}' \
    '\            @apply(--tf-regex-group-regex-inpput);'

block-insert \
    priv/components/tf-dashboard-common/tf-option-selector.html \
    '<style>' '<\/style>' \
    '\      .content-wrapper { @apply(--tf-option-selector-content-wrapper); }'

block-insert \
    priv/components/tf-dashboard-common/dashboard-style.html \
    '.sidebar-section {' '}' \
    '\        @apply(--tf-dashboard-style-sidebar-section);'

block-insert \
    priv/components/tf-dashboard-common/tf-collapsable-pane.html \
    '.heading {' '}' \
    '\        @apply(--tf-collapsable-pane-heading);'

block-insert \
    priv/components/tf-dashboard-common/tf-collapsable-pane.html \
    ':host {' '}' \
    '\        @apply(--tf-collapsable-pane);'

block-insert \
    priv/components/tf-dashboard-common/tf-collapsable-pane.html \
    ':host:first-of-type {' '}' \
    '\        @apply(--tf-collapsable-pane-first);'

block-insert \
    priv/components/tf-dashboard-common/tf-categorizer.html \
    ':host {' '}' \
    '\        @apply(--tf-categorizer);'

block-insert \
    priv/components/tf-dashboard-common/tf-categorizer.html \
    '#underscore-categorization {' '}' \
    '\        @apply(--tf-categorizer-underscore-categorization);'

block-insert \
    priv/components/tf-graph/tf-graph-controls.html \
    '.allcontrols {' '}' \
    '\  @apply(--tf-graph-controls-allcontrols);'
