#!/bin/bash -eu

# Remove imports of roboto.html which incur a dependency on Google's CDN
# See https://github.com/PolymerElements/paper-styles/pull/128
sed -i /roboto.html/d priv/components/paper-styles/typography.html

# Remove import of iron-flex-layout/classes
# See https://github.com/PolymerElements/paper-styles/issues/49
sed -i /iron-flex-layout\\/classes\\/iron-flex-layout.html/d priv/components/paper-styles/paper-styles.html
