#!/bin/bash

TF_HOME=${TF_HOME:-../tensorflow}

components=(
    tf_backend
    tf_color_scale
    tf_dashboard_common
    tf_globals
    tf_imports
    tf_scalar_dashboard
    tf_storage
    vz_line_chart
    vz_sorting
)

function component-src() {
    echo $TF_HOME/tensorflow/tensorboard/components/$c
}

function component-dest() {
    echo priv/components/${c//_/-}
}

for c in ${components[@]}; do
    rsync -a --delete --info=name $(component-src $c)/ $(component-dest $c)/
done
