#!/usr/bin/env escript
%%-*-erlang-*-
%%! -env ERL_LIBS build/default/lib

main(Args) ->
    try
        run_tests(Args)
    catch
        _:Err ->
            print_error(Err, erlang:get_stacktrace()),
            erlang:halt(1)
    end.

run_tests([]) ->
    hubc_tests:run();
run_tests(Tests) ->
    lists:foreach(fun hubc_tests:run/1, Tests).

print_error(Err, Stack) ->
    io:format("ERROR~n"),
    print_file_and_line(Err, Stack),
    io:format("~p~n", [Stack]).

print_file_and_line(Err, Stack) ->
    case last_file_info(Stack) of
        {File, Line} ->
            io:format("~s:~b: ~99999p~n", [shorten_file(File), Line, Err]);
        error ->
            io:format("~99999p~n", [Err])
    end.

last_file_info([{_, _, _, Attrs}|Rest]) ->
    case proplists:get_value(file, Attrs) of
        undefined -> last_file_info(Rest);
        File -> {File, proplists:get_value(line, Attrs)}
    end;
last_file_info([]) ->
    error.

shorten_file(File) ->
    re:replace(File, "^.*/build/default/lib/tensorhub_client/", "").
